name: FRA Replication
on: [push]
jobs:
  Job1:
    runs-on:
      - codebuild-StaleRunner-20826674918-1
    steps:
      - run: echo "Hello World!"
      - run: sleep 12
  Hello-New-Job:
    runs-on:
      - codebuild-CustomImage5678-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello New World 1!"
      - run: "ls "
