name: SIN Replication
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-TestRunner1-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World!"
      - run: sleep 3
  Hello-New-Job:
    runs-on:
      - codebuild-TestRunner2-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello New World 1!"
      - run: "ls "
